/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedEmailTemplatesRouteImport } from './routes/_authenticated/email-templates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCareersRouteImport } from './routes/_authenticated/careers'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as CSlugIndexRouteImport } from './routes/c/$slug/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates/index'
import { Route as AuthenticatedAiIndexRouteImport } from './routes/_authenticated/ai/index'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings/team'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedSettingsBrandingRouteImport } from './routes/_authenticated/settings/branding'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs/new'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs/$id'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates/$id'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications/$id'
import { Route as AuthenticatedAiScoringRouteImport } from './routes/_authenticated/ai/scoring'
import { Route as AuthenticatedAiResumeParserRouteImport } from './routes/_authenticated/ai/resume-parser'
import { Route as CSlugCareersIndexRouteImport } from './routes/c/$slug/careers/index'
import { Route as CSlugJobsJobIdRouteImport } from './routes/c/$slug/jobs/$jobId'
import { Route as CSlugCareersJobsJobIdRouteImport } from './routes/c/$slug/careers/jobs/$jobId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailTemplatesRoute =
  AuthenticatedEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareersRoute = AuthenticatedCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CSlugIndexRoute = CSlugIndexRouteImport.update({
  id: '/c/$slug/',
  path: '/c/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiIndexRoute = AuthenticatedAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBrandingRoute =
  AuthenticatedSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiScoringRoute = AuthenticatedAiScoringRouteImport.update({
  id: '/ai/scoring',
  path: '/ai/scoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiResumeParserRoute =
  AuthenticatedAiResumeParserRouteImport.update({
    id: '/ai/resume-parser',
    path: '/ai/resume-parser',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CSlugCareersIndexRoute = CSlugCareersIndexRouteImport.update({
  id: '/c/$slug/careers/',
  path: '/c/$slug/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugJobsJobIdRoute = CSlugJobsJobIdRouteImport.update({
  id: '/c/$slug/jobs/$jobId',
  path: '/c/$slug/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugCareersJobsJobIdRoute = CSlugCareersJobsJobIdRouteImport.update({
  id: '/c/$slug/careers/jobs/$jobId',
  path: '/c/$slug/careers/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/automations': typeof AuthenticatedAutomationsRoute
  '/careers': typeof AuthenticatedCareersRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/join/$token': typeof JoinTokenRoute
  '/ai/resume-parser': typeof AuthenticatedAiResumeParserRoute
  '/ai/scoring': typeof AuthenticatedAiScoringRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/ai/': typeof AuthenticatedAiIndexRoute
  '/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/jobs/$jobId': typeof CSlugJobsJobIdRoute
  '/c/$slug/careers/': typeof CSlugCareersIndexRoute
  '/c/$slug/careers/jobs/$jobId': typeof CSlugCareersJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/careers': typeof AuthenticatedCareersRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/join/$token': typeof JoinTokenRoute
  '/ai/resume-parser': typeof AuthenticatedAiResumeParserRoute
  '/ai/scoring': typeof AuthenticatedAiScoringRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/ai': typeof AuthenticatedAiIndexRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/c/$slug': typeof CSlugIndexRoute
  '/c/$slug/jobs/$jobId': typeof CSlugJobsJobIdRoute
  '/c/$slug/careers': typeof CSlugCareersIndexRoute
  '/c/$slug/careers/jobs/$jobId': typeof CSlugCareersJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/careers': typeof AuthenticatedCareersRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/join/$token': typeof JoinTokenRoute
  '/_authenticated/ai/resume-parser': typeof AuthenticatedAiResumeParserRoute
  '/_authenticated/ai/scoring': typeof AuthenticatedAiScoringRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/ai/': typeof AuthenticatedAiIndexRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/jobs/$jobId': typeof CSlugJobsJobIdRoute
  '/c/$slug/careers/': typeof CSlugCareersIndexRoute
  '/c/$slug/careers/jobs/$jobId': typeof CSlugCareersJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/settings'
    | '/automations'
    | '/careers'
    | '/crm'
    | '/dashboard'
    | '/email-templates'
    | '/employees'
    | '/interviews'
    | '/offers'
    | '/pipeline'
    | '/join/$token'
    | '/ai/resume-parser'
    | '/ai/scoring'
    | '/applications/$id'
    | '/candidates/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/settings/branding'
    | '/settings/integrations'
    | '/settings/team'
    | '/ai/'
    | '/candidates/'
    | '/jobs/'
    | '/settings/'
    | '/c/$slug/'
    | '/c/$slug/jobs/$jobId'
    | '/c/$slug/careers/'
    | '/c/$slug/careers/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/automations'
    | '/careers'
    | '/crm'
    | '/dashboard'
    | '/email-templates'
    | '/employees'
    | '/interviews'
    | '/offers'
    | '/pipeline'
    | '/join/$token'
    | '/ai/resume-parser'
    | '/ai/scoring'
    | '/applications/$id'
    | '/candidates/$id'
    | '/jobs/$id'
    | '/jobs/new'
    | '/settings/branding'
    | '/settings/integrations'
    | '/settings/team'
    | '/ai'
    | '/candidates'
    | '/jobs'
    | '/settings'
    | '/c/$slug'
    | '/c/$slug/jobs/$jobId'
    | '/c/$slug/careers'
    | '/c/$slug/careers/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_authenticated/settings'
    | '/_authenticated/automations'
    | '/_authenticated/careers'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-templates'
    | '/_authenticated/employees'
    | '/_authenticated/interviews'
    | '/_authenticated/offers'
    | '/_authenticated/pipeline'
    | '/join/$token'
    | '/_authenticated/ai/resume-parser'
    | '/_authenticated/ai/scoring'
    | '/_authenticated/applications/$id'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/jobs/new'
    | '/_authenticated/settings/branding'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/team'
    | '/_authenticated/ai/'
    | '/_authenticated/candidates/'
    | '/_authenticated/jobs/'
    | '/_authenticated/settings/'
    | '/c/$slug/'
    | '/c/$slug/jobs/$jobId'
    | '/c/$slug/careers/'
    | '/c/$slug/careers/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JoinTokenRoute: typeof JoinTokenRoute
  CSlugIndexRoute: typeof CSlugIndexRoute
  CSlugJobsJobIdRoute: typeof CSlugJobsJobIdRoute
  CSlugCareersIndexRoute: typeof CSlugCareersIndexRoute
  CSlugCareersJobsJobIdRoute: typeof CSlugCareersJobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-templates': {
      id: '/_authenticated/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof AuthenticatedEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/careers': {
      id: '/_authenticated/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AuthenticatedCareersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$slug/': {
      id: '/c/$slug/'
      path: '/c/$slug'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof CSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/': {
      id: '/_authenticated/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AuthenticatedAiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/branding': {
      id: '/_authenticated/settings/branding'
      path: '/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AuthenticatedSettingsBrandingRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/scoring': {
      id: '/_authenticated/ai/scoring'
      path: '/ai/scoring'
      fullPath: '/ai/scoring'
      preLoaderRoute: typeof AuthenticatedAiScoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/resume-parser': {
      id: '/_authenticated/ai/resume-parser'
      path: '/ai/resume-parser'
      fullPath: '/ai/resume-parser'
      preLoaderRoute: typeof AuthenticatedAiResumeParserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$slug/careers/': {
      id: '/c/$slug/careers/'
      path: '/c/$slug/careers'
      fullPath: '/c/$slug/careers/'
      preLoaderRoute: typeof CSlugCareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/jobs/$jobId': {
      id: '/c/$slug/jobs/$jobId'
      path: '/c/$slug/jobs/$jobId'
      fullPath: '/c/$slug/jobs/$jobId'
      preLoaderRoute: typeof CSlugJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/careers/jobs/$jobId': {
      id: '/c/$slug/careers/jobs/$jobId'
      path: '/c/$slug/careers/jobs/$jobId'
      fullPath: '/c/$slug/careers/jobs/$jobId'
      preLoaderRoute: typeof CSlugCareersJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsBrandingRoute: typeof AuthenticatedSettingsBrandingRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsBrandingRoute: AuthenticatedSettingsBrandingRoute,
    AuthenticatedSettingsIntegrationsRoute:
      AuthenticatedSettingsIntegrationsRoute,
    AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedCareersRoute: typeof AuthenticatedCareersRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailTemplatesRoute: typeof AuthenticatedEmailTemplatesRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedAiResumeParserRoute: typeof AuthenticatedAiResumeParserRoute
  AuthenticatedAiScoringRoute: typeof AuthenticatedAiScoringRoute
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedAiIndexRoute: typeof AuthenticatedAiIndexRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedCareersRoute: AuthenticatedCareersRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailTemplatesRoute: AuthenticatedEmailTemplatesRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedAiResumeParserRoute: AuthenticatedAiResumeParserRoute,
  AuthenticatedAiScoringRoute: AuthenticatedAiScoringRoute,
  AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedAiIndexRoute: AuthenticatedAiIndexRoute,
  AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JoinTokenRoute: JoinTokenRoute,
  CSlugIndexRoute: CSlugIndexRoute,
  CSlugJobsJobIdRoute: CSlugJobsJobIdRoute,
  CSlugCareersIndexRoute: CSlugCareersIndexRoute,
  CSlugCareersJobsJobIdRoute: CSlugCareersJobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
